import { Database, Layers, BookOpen, Cpu, Code, Network, ShieldCheck, Briefcase } from "lucide-react";

export const experienceItems = [
    {
        title: "Java-based Inventory Tool",
        slug: "java-inventory-tool",
        type: "Software Development",
        description: "Built a Java-based inventory tool handling 500+ items.",
        expandedDetails: "Developed an object-oriented Java application with a robust backend focusing on data structure optimization.",
        icon: <Database className="w-6 h-6 text-[#00ccff]" />,
        color: "from-[#00ccff] to-blue-600",
    },
    {
        title: "Unity Asset Optimization",
        slug: "unity-asset-optimization",
        type: "Game Development",
        description: "Optimized Unity assets to boost frame rates by 20 FPS.",
        expandedDetails: "Restructured 3D assets and optimized rendering pipelines, reducing memory overhead.",
        icon: <Layers className="w-6 h-6 text-[#ff3366]" />,
        color: "from-[#ff3366] to-red-600",
    },
    {
        title: "Technical Workshops",
        slug: "technical-workshops",
        type: "Leadership",
        description: "Facilitated technical workshops for 30+ peers.",
        expandedDetails: "Organized and facilitated interactive technical sessions, mentoring peers in advanced programming concepts.",
        icon: <BookOpen className="w-6 h-6 text-green-400" />,
        color: "from-green-400 to-emerald-600",
    },
    {
        title: "Automated Data Analysis",
        slug: "automated-data-analysis",
        type: "Data Engineering",
        description: "Automated data analysis, saving 5 hours/week.",
        expandedDetails: "Engineered script-based automation tools for complex workflows, eliminating redundant tasks.",
        icon: <Database className="w-6 h-6 text-purple-400" />,
        color: "from-purple-400 to-indigo-600",
    },
    {
        title: "Haptic Feedback Integration",
        slug: "haptic-feedback-integration",
        type: "Mechatronics",
        description: "Integrated Haptic Feedback with sub-10ms latency.",
        expandedDetails: "Programmed advanced haptic feedback mechanisms into mechatronic systems for real-time tactile response.",
        icon: <Cpu className="w-6 h-6 text-yellow-400" />,
        color: "from-yellow-400 to-orange-600",
    },
    {
        title: "Digital Memory Architecture",
        slug: "digital-memory-architecture",
        type: "Hardware Design",
        description: "Designed and simulated digital memory architecture using Matlab.",
        expandedDetails: "Designed and rigorously simulated a RAM Decoder utilizing MATLAB, bridging hardware logic with software.",
        icon: <Cpu className="w-6 h-6 text-[#00ccff]" />,
        color: "from-[#00ccff] to-blue-600",
    },
    {
        title: "C# Algorithms for Unity",
        slug: "csharp-algorithms-unity",
        type: "Software Development",
        description: "Developed efficient C# algorithms for Unity.",
        expandedDetails: "Authored scalable C# scripts to drive complex game mechanics and physics simulations.",
        icon: <Code className="w-6 h-6 text-[#ff3366]" />,
        color: "from-[#ff3366] to-red-600",
    },
    {
        title: "Metaverse VR Immersion",
        slug: "metaverse-vr-immersion",
        type: "Virtual Reality",
        description: "Contributed to a Metaverse project focusing on VR.",
        expandedDetails: "Developed spatial computing mechanics to enhance user immersion within VR environments.",
        icon: <Network className="w-6 h-6 text-green-400" />,
        color: "from-green-400 to-emerald-600",
    },
    {
        title: "Global Cybersecurity Certification",
        slug: "cybersecurity-certification",
        type: "Security",
        description: "Secured Global Cybersecurity certification (Top 10%).",
        expandedDetails: "Demonstrated strong foundational knowledge in network security and vulnerability scanning.",
        icon: <ShieldCheck className="w-6 h-6 text-purple-400" />,
        color: "from-purple-400 to-indigo-600",
    },
    {
        title: "University Project Lead",
        slug: "university-project-lead",
        type: "Leadership",
        description: "Lead a university project team of 4 engineers.",
        expandedDetails: "Directed a cross-functional team, managing project lifecycles and technical architecture.",
        icon: <Briefcase className="w-6 h-6 text-yellow-400" />,
        color: "from-yellow-400 to-orange-600",
    },
];
